OBJS = jetan.c logic.c moves.c board.c array.c util.c visual.c
CC = gcc
COMPILER_FLAGS = -w
LINKER_FLAGS = -lSDL2
OBJ_NAME = ../bin/jetan

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
